pythontube/posts/urls.py
from django.urls import path

from posts.views import *


app_name = 'posts'
urlpatterns = [
    path('', PostListView.as_view(), name="list"),
    path('new/', PostCreateView.as_view(), name="create"),
    path('confirm/', PostCreateConfirmView.as_view(), name="confirm"),
    path('<slug:slug>/', PostDetailView.as_view(), name="detail"),

]

pythontube/pythontube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('social_django.urls', namespace='social')),

    path('', include("users.urls", namespace="users")),

    path('posts/', include("posts.urls", namespace="posts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pythontube/users/urls.py
from django.urls import path, include

from users.views import *


app_name = 'users'
urlpatterns = [
    path('signup/', SignupView.as_view(), name="signup"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

pythontube/pythontube/templates/partials/footer.html
<footer>
    <h1>footer</h1>
</footer>

pythontube/pythontube/templates/partials/header.html
<header>
    <h1>Header</h1>

    <ul>
        {% if request.user.is_authenticated %}
        <li>
            <a href="{% url "users:logout" %}">Logout</a>
        </li>
        {% else %}
        <li>
            <a href="{% url "social:begin" "github" %}">Github으로 로그인 하기</a>
        </li>
        <li>
            <a href="{% url "users:login" %}">Login</a>
        </li>
        <li>
            <a href="{% url "users:signup" %}">Sign up</a>
        </li>
        {% endif %}
    </ul>
</header>

pythontube/pythontube/templates/partials/messages.html
{% if messages %}
    <section id="messages">
        <ul>
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    <p>{{ message }}</p>
                </li>
            {% endfor %}
        </ul>
    </section>  
{% endif %}
